apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
    version: 1.2.2_coreos.0
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-scheduler
        version: 1.2.2_coreos.0
    spec:
      nodeSelector:
        master: "true"
      hostNetwork: true
      containers:
      - name: kube-scheduler
        image: quay.io/coreos/hyperkube:v1.2.2_coreos.0
        command:
        - ./hyperkube
        - scheduler
        - --master=127.0.0.1:8080
        - --leader-elect=true
