apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: {{ .Server }}
    certificate-authority-data: {{ .CACert }}
users:
- name: k8s
  user:
    token: {{ .Token }}
contexts:
- context:
    cluster: local
    user: k8s
